from digitsnn.digits_recognition_neural_network import DigitsRecognitionNeuralNetwork
from digitsnn.digits_generation_neural_network import DigitsGenerationNeuralNetwork
from digitsnn.digits_recognition_qt import display_digit
